### ISSUE TITLE
HotTowelRouteConfig breaks non-breeze webapi controllers

### ISSUE THREAD

**Issue by DanHarman** [johnpapa/HotTowel#11] opened 2013-04-01 16:23 UTC
Using the vsix to create a hot towel app, any webapi controllers that are added will not resolve.

This seems to be because a route with hot towel defaults is being slammed to the front of the table so pretty much everything resolves to it. An easy fix is to modify the standard routeconfig default route and remove the hot towel one. Also the BreezeWebApiConfig is a little surprising in its behaviour for anyone who wasn't planning to go solely with breeze.

Was definitely surprised by this behaviour and took quite some time to find the culprit. If it is intended, a comment to explain that standard mvc and webapi conventions have just been nuked would be helpful.

**Comment by mattjohnsonpint** [comment] 2013-04-02 23:44
Dup of: https://github.com/johnpapa/HotTowel/issues/2

**Comment by DanHarman** [comment] 2013-04-06 17:44
Ah I didn't spot that as it was closed. Strikes me as a clear breach of the principal of least astonishment!

**Comment by talves** [comment] 2013-07-24 20:33
I just spent hours on this same issue.  Found the culprit as Dan did and wished someone would have fixed this four months ago.  On the bright side, I understand routing better than I did when this bug was happening.

**Comment by johnpapa** [comment] 2013-07-24 20:35
closed as a duplicate of #2

**Closed as completed** 2013-07-24 20:35 UTC
